import sys
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          
x=open(sys.argv[1],"r")                                                                                                                                                                                                                      
lines=x.readlines()                                                                                                                                                                                                                          
x.close()                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                             
latinweb='<a href="http://www.perseus.tufts.edu/hopper/morph?l=REPLACEME&la=la">REPLACEME</a>'                                                                                                                                                                                                                                                                                                                                                                                           
                                                                                                                                                                                                                                             
print("<html>")                                                                                                                                                                                                                              
                                                                                                                                                                                                                                             
for l in lines:                                                                                                                                                                                                                              
   print("<p>")                                                                                                                                                                                                                              
   l=l.split(" ")                                                                                                                                                                                                                            
   all=""                                                                                                                                                                                                                                    
   for word in l:                                                                                                                                                                                                                            
     latinize=latinweb.replace("REPLACEME",word.rstrip())                                                                                                                                                                                    
     all=all+latinize+" "                                                                                                                                                                                                                    
   print(all)                                                                                                                                                                                                                                
   print(f"\n")                                                                                                                                                                                                                              
   print("</p>")                                                                                                                                                                                                                             
print("</html>")
